import {CLASSES,ENEMIES,ROOMS,RELICS,ITEMS,UPGRADES,SLOT_NAMES,ACHIEVEMENTS} from '../data/content.js';
import {stats,upgradeCost} from '../systems/progression.js';
import {intent,skillCost} from '../systems/combat.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const btn=(label,action,value='',cls='',disabled=false)=>'<button class="'+cls+'" data-action="'+action+'" data-value="'+esc(value)+'" '+(disabled?'disabled':'')+'>'+label+'</button>';
export const art=(key,label,cls='',lazy=false)=>'<img class="art '+cls+'" src="./assets/'+key+'.webp" alt="'+esc(label)+'" '+(lazy?'loading="lazy"':'')+' draggable="false">';
const bar=(value,max,label,cls='')=>'<div class="meter '+cls+'" role="progressbar" aria-label="'+label+'" aria-valuenow="'+value+'" aria-valuemax="'+max+'" aria-valuemin="0"><i style="width:'+Math.min(100,Math.max(0,value/max*100))+'%"></i></div>';
const small=(a,b)=>'<span class="eyebrow">'+a+'</span><h2>'+b+'</h2>';
export function header(s){return '<header class="topbar"><button class="brand" data-action="home" aria-label="타이틀로 이동"><span class="brand-mark">D</span><span>ONE MINUTE <b>DUNGEON <em>RE</em></b></span></button><div class="top-tools"><span class="wallet">'+s.totalGold.toLocaleString()+' <small>G</small></span>'+btn('도움말','modal','help','quiet')+btn(s.settings.sound?'소리 켜짐':'소리 꺼짐','sound','','quiet')+'</div></header>';}
export function title(s){
 const c=CLASSES[s.lastClass],active=s.run&&s.run.phase!=='result';
 return '<main class="title-screen"><section class="title-art"><div class="title-copy"><p class="eyebrow">A LITTLE ADVENTURE. A NEW BEGINNING.</p><h1>ONE MINUTE<br><strong>DUNGEON</strong><span class="re-stamp">RE</span></h1><p class="tagline">다시, 던전의 문 앞에서.</p></div><div class="hero-display">'+art(s.lastClass,c.name,'title-hero')+'<div class="hero-caption"><span>THE EMBER SANCTUARY</span><b>잔불의 성소</b></div></div><div class="title-foot"><span>짧은 탐험, 깊은 선택.</span><span>한 판 약 3–5분</span></div></section><section class="title-panel">'+small('CHOOSE YOUR ADVENTURER','누구의 이야기를 시작할까요?')+'<div class="class-grid">'+Object.entries(CLASSES).map(([k,v])=>'<button class="class-card '+(s.lastClass===k?'selected':'')+'" data-action="class" data-value="'+k+'" aria-pressed="'+(s.lastClass===k)+'" '+(active?'disabled':'')+'>'+art(k,v.name,'',k!==s.lastClass)+'<strong>'+v.name+'</strong><small>'+v.role+'</small></button>').join('')+'</div><div class="class-detail"><span class="eyebrow">'+c.title+'</span><h3>'+c.skill+'</h3><p>'+c.desc+'</p><div class="stat-line"><span>HP <b>'+stats(s).maxHp+'</b></span><span>공격 <b>'+stats(s).atk+'</b></span><span>방어 <b>'+stats(s).def+'</b></span></div></div><label class="difficulty">탐험 난도<select id="difficulty" '+(active?'disabled':'')+'>'+[0,1,2,3].map(n=>'<option value="'+n+'" '+(s.difficulty===n?'selected':'')+'>'+['첫 번째 불꽃','깊어진 어둠 · 적 +18%','잿빛 시련 · 적 +36%','심연 · 적 +54%'][n]+'</option>').join('')+'</select></label>'+btn(active?'탐험 이어하기 <span>→</span>':'던전 입장 <span>→</span>',active?'resume':'start','','primary enter')+'<p class="subtle center">적의 다음 행동을 읽고, 나만의 길을 선택하세요.</p><nav class="meta-nav">'+btn('영구 성장','modal','upgrades')+btn('장비','modal','inventory')+btn('도감·업적','modal','collection')+'</nav><div class="records"><div><b>'+s.playCount+'</b><span>완료한 탐험</span></div><div><b>'+s.clearCount+'</b><span>클리어</span></div><div><b>'+(s.bestClearTime===null?'—':s.bestClearTime+'s')+'</b><span>최단 기록</span></div></div></section></main>';
}
function mapMarkup(r,compact=false){
 return '<div class="dungeon-map '+(compact?'compact':'')+'">'+r.map.map((row,i)=>'<div class="map-row '+(i<=r.depth?'visited':'')+'"><span class="floor">'+String(i+1).padStart(2,'0')+'</span><div class="nodes">'+row.map((type,j)=>{const d=ROOMS[type],current=i===r.depth+1&&r.phase==='map',selected=r.path[i]===j;return '<button class="node '+d.tone+' '+(selected?'chosen':'')+' '+(current?'available':'')+'" data-action="room" data-value="'+j+'" '+(!current?'disabled':'')+' aria-label="'+(i+1)+'구간 '+d.name+(selected?' 방문함':'')+'"><span>'+d.symbol+'</span><b>'+d.name+'</b>'+(compact?'':'<small>'+d.desc+'</small>')+(selected?'<i>✓</i>':'')+'</button>';}).join('')+'</div></div>').join('')+'</div>';
}
function playerPanel(s){
 const r=s.run,c=CLASSES[r.classKey],st=stats(s,r);
 return '<aside class="player-panel"><p class="eyebrow">ADVENTURER</p><div class="player-identity">'+art(r.classKey,c.name)+'<div><small>'+c.title+'</small><h2>'+c.name+'</h2></div></div><div class="stat-line"><span>공격 <b>'+st.atk+'</b></span><span>방어 <b>'+st.def+'</b></span><span>치명 <b>'+Math.round(st.crit*100)+'%</b></span></div><h3 class="section-label">장비</h3>'+Object.entries(s.equipped).map(([slot,id])=>'<button class="equip-slot" data-action="modal" data-value="inventory"><span>'+SLOT_NAMES[slot]+'</span><b>'+(ITEMS[id]?.name||'미장착')+'</b></button>').join('')+'<h3 class="section-label">클래스 스킬</h3><p class="skill-name">'+c.skill+'</p><p class="subtle">'+c.skillDesc+'</p><div class="field-notes"><p class="eyebrow">FIELD NOTES</p><p>강공격 전에는 방어.<br>빈틈이 보이면 스킬.<br>살아남는 것도 하나의 선택.</p></div>'+btn('탐험 귀환','modal','abandon','quiet')+'</aside>';
}
function buildPanel(r){return '<aside class="build-panel"><div class="section-heading"><span class="eyebrow">EXPEDITION</span><b>'+Math.max(1,r.depth+1)+' / 9</b></div>'+mapMarkup(r,true)+'<h3 class="section-label">이번 탐험의 유물 <span>'+r.relics.length+'</span></h3><div class="relic-list">'+(r.relics.length?r.relics.map(k=>'<div><b>'+RELICS[k].name+'</b><small>'+RELICS[k].desc+'</small></div>').join(''):'<p class="subtle">4·7구간에서 유물을 선택합니다.</p>')+'</div>'+(r.relics.includes('ember')&&r.relics.includes('lens')?'<p class="synergy">별불꽃 공명 · 스킬 +6</p>':'')+'</aside>';}
function hud(s){
 const r=s.run,st=stats(s,r),c=CLASSES[r.classKey];
 return '<div class="player-hud"><div class="resource"><div><b>HP</b><span>'+r.hp+' / '+st.maxHp+'</span></div>'+bar(r.hp,st.maxHp,'플레이어 HP',r.hp/st.maxHp<.3?'low':'health')+'</div><div class="resource energy"><div><b>'+(r.classKey==='mage'?'마나':'기력')+'</b><span>'+r.energy+' / '+c.maxEnergy+'</span></div>'+bar(r.energy,c.maxEnergy,'행동 자원','mana')+'</div><div class="run-gold">'+r.gold+' <small>G</small></div></div>';
}
function combat(s,busy){
 const r=s.run,e=r.enemy,d=ENEMIES[e.key],m=intent(r),c=CLASSES[r.classKey];
 return '<div class="arena '+(e.type==='boss'?'boss-arena '+(e.turn===0?'boss-enter':''):'')+'"><div class="enemy-info"><span class="eyebrow">'+(e.type==='boss'?'BOSS · '+(e.phase===2?'격노':'잔불의 군주'):e.type==='elite'?'ELITE ENCOUNTER':'ENCOUNTER')+'</span><h2>'+d.name+'</h2>'+bar(e.hp,e.maxHp,'적 HP','enemy-health')+'<small>'+e.hp+' / '+e.maxHp+' HP</small><div class="status-tags">'+(e.poison?'<span>독 '+e.poison+'턴</span>':'')+(e.burn?'<span>화상 '+e.burn+'턴</span>':'')+'</div></div><div class="intent '+(m.damage>25?'danger':'')+'"><b>다음 행동 · '+m.label+(m.damage?' '+m.damage:'')+'</b><small>'+m.hint+'</small></div><div class="fighter enemy-fighter" id="enemy-art">'+art(d.art,d.name)+'<span class="damage-anchor"></span></div><div class="fighter player-fighter" id="player-art">'+art(r.classKey,c.name)+'<span class="damage-anchor"></span></div><span class="turn-counter">TURN '+(e.turn+1)+'</span><div class="player-status">'+(r.focus?'<span>반격 준비</span>':'')+(r.poison?'<span>중독 '+r.poison+'턴</span>':'')+(r.burn?'<span>화상 '+r.burn+'턴</span>':'')+'</div></div>'+hud(s)+'<div class="combat-actions">'+btn('<kbd>1</kbd><b>공격</b><small>자원 +1</small>','act','attack','attack',busy)+btn('<kbd>2</kbd><b>'+c.skill+'</b><small>자원 '+skillCost(r)+' 소모</small>','act','skill','skill',busy||r.energy<skillCost(r))+btn('<kbd>3</kbd><b>방어</b><small>피해 75% 감소</small>','act','guard','guard',busy)+btn('<kbd>4</kbd><b>물약 ×'+r.potions+'</b><small>HP 40% · 정화</small>','act','potion','potion',busy||!r.potions||r.hp>=stats(s,r).maxHp)+'</div><p class="action-help">방어는 상태이상을 해제하고 자원을 회복합니다. 물약도 한 턴을 사용합니다.</p>';
}
function roomView(s){
 const r=s.run,meta=ROOMS[r.room];
 if(r.phase==='map')return '<div class="map-view">'+small('CHOOSE YOUR PATH','어떤 길을 택할까요?')+'<p class="subtle">빛나는 다음 구간을 선택하세요. 선택하지 않은 길은 지나칩니다.</p>'+mapMarkup(r)+'</div>'+hud(s);
 if(r.phase==='reward')return '<div class="room-view reward-view"><span class="room-sigil">◇</span>'+small('A MOMENT OF TRIUMPH',r.room==='treasure'?'잊힌 보물을 찾았습니다':'한 걸음 더 깊은 곳으로')+'<p>'+esc(r.log[0])+'</p>'+(r.loot?itemCard(r.loot,s,true):'')+btn('다음 길 선택 <span>→</span>','next','','primary')+'</div>'+hud(s);
 let choices='';
 if(r.room==='relic')choices=r.choices.map(k=>btn('<span class="eyebrow">'+RELICS[k].rarity+' · '+RELICS[k].tag+'</span><b>'+RELICS[k].name+'</b><small>'+RELICS[k].desc+'</small>','choose',k,'choice-card')).join('');
 if(r.room==='rest')choices=btn('<b>불가에서 쉬기</b><small>최대 HP의 40% 회복</small>','choose','heal','choice-card')+btn('<b>물약 챙기기</b><small>회복 물약 +1</small>','choose','potion','choice-card');
 if(r.room==='event')choices=btn('<b>제단과 계약하기</b><small>HP 18 소모 · 이번 판 공격력 +3</small>','choose','sacrifice','choice-card',r.hp<=18)+btn('<b>지나치기</b><small>체력을 지키고 다음 길로</small>','choose','leave','choice-card');
 if(r.room==='shop')choices=btn('<b>회복 물약</b><small>25 G · 현재 '+r.potions+'개</small>','choose','potion','choice-card',r.gold<25)+btn('<b>황혼의 망토</b><small>45 G · 방어 +2 / HP +12</small>','choose','dusk','choice-card',r.gold<45||s.inventory.includes('dusk'))+btn('상점 나가기','choose','leave','quiet');
 return '<div class="room-view"><span class="room-sigil">'+meta.symbol+'</span>'+small('THE EMBER SANCTUARY',meta.name)+'<p class="subtle">'+meta.desc+'</p><div class="choices">'+choices+'</div></div>'+hud(s);
}
export function game(s,busy){
 const r=s.run;
 if(r.phase==='result')return result(s);
 return '<main class="game-layout">'+playerPanel(s)+'<section class="game-center"><div class="chapter-bar"><span>잔불의 성소 <small> / '+(r.difficulty+1)+'단계</small></span><b>'+String(Math.max(1,r.depth+1)).padStart(2,'0')+' <small>/ 09</small></b></div>'+(r.phase==='combat'?combat(s,busy):roomView(s))+'<div class="mobile-tools">'+btn('장비·가방','modal','inventory')+btn('유물','modal','relics')+btn('전투 기록','modal','log')+'</div><div class="battle-log" aria-label="최근 기록">'+r.log.slice(0,3).map((x,i)=>'<p class="'+(i===0?'latest':'')+'">'+esc(x)+'</p>').join('')+'</div></section>'+buildPanel(r)+'</main>';
}
function result(s){const r=s.run;return '<main class="result-screen '+(r.victory?'victory':'')+'"><p class="eyebrow">'+(r.victory?'THE FLAME LIVES ON':'EVERY END IS A BEGINNING')+'</p><h1>'+(r.victory?'잔불은 꺼지지 않는다.':'다음엔, 더 깊은 곳으로.')+'</h1><p>'+(r.victory?'성소의 군주를 쓰러뜨렸습니다.':esc(r.reason))+'</p>'+art(r.classKey,CLASSES[r.classKey].name)+'<div class="result-stats"><div><span>획득 골드</span><b>+'+r.earned+' G</b></div><div><span>도달 구간</span><b>'+(r.depth+1)+' / 9</b></div><div><span>처치</span><b>'+r.kills+'</b></div><div><span>탐험 시간</span><b>'+Math.floor(r.elapsed/60)+'분 '+r.elapsed%60+'초</b></div></div>'+(r.victory?'<p class="synergy">영웅 장비 · 잔불의 왕관 획득</p>':'')+(r.newAchievements.length?'<p>새 업적 · '+r.newAchievements.map(esc).join(' / ')+'</p>':'')+'<div class="result-actions">'+btn('다시 도전','start','','primary')+btn('성장하고 준비하기','home','','secondary')+'</div><p class="subtle">획득한 장비와 골드는 다음 모험에도 남습니다.</p></main>';}
export function itemCard(id,s,compact=false){const d=ITEMS[id];if(!d)return '';const equipped=s.equipped[d.slot]===id;return '<article class="item-card '+(equipped?'equipped':'')+'"><span class="eyebrow">'+d.rarity+' · '+SLOT_NAMES[d.slot]+'</span><h3>'+d.name+'</h3><p>'+d.desc+'</p>'+btn(equipped?'장착 중 · 해제':'장착','equip',id,compact?'quiet':'secondary')+'</article>';}
export function modalContent(name,s){
 const r=s.run;
 if(name==='inventory')return {title:'장비와 가방',body:'<p class="subtle">장비는 영구 보관됩니다. 장착 변경은 현재 탐험에도 적용됩니다.</p><div class="card-grid">'+(s.inventory.length?s.inventory.map(k=>itemCard(k,s)).join(''):'<p>보물방과 정예 전투에서 장비를 얻으세요.</p>')+'</div>'};
 if(name==='upgrades')return {title:'영구 성장',body:'<p class="wallet">보유 '+s.totalGold+' G</p><p class="subtle">성장은 다음 탐험부터 적용됩니다.</p><div class="card-grid">'+Object.entries(UPGRADES).map(([k,d])=>'<article class="item-card"><span class="eyebrow">LEVEL '+s.upgrades[k]+' / '+d.max+'</span><h3>'+d.name+'</h3><p>'+d.desc+'</p>'+btn(s.upgrades[k]>=d.max?'최대 레벨':upgradeCost(s,k)+' G · 강화','upgrade',k,'secondary',!!r||s.upgrades[k]>=d.max||s.totalGold<upgradeCost(s,k))+'</article>').join('')+'</div>'};
 if(name==='collection')return {title:'모험의 기록',body:'<h3>도감</h3><div class="card-grid">'+Object.entries(ENEMIES).map(([k,d])=>'<article class="item-card">'+(s.bestiary.includes(k)?art(d.art,d.name,'codex-art',true)+'<h3>'+d.name+'</h3><p>'+d.desc+'</p><small>처치 '+(s.killCounts[k]||0)+'회</small>':'<h3>미발견</h3><p>던전에서 이 적을 처치하세요.</p>')+'</article>').join('')+'</div><h3>업적</h3>'+ACHIEVEMENTS.map(a=>'<p class="achievement">'+(s.achievements.includes(a.id)?'✓':'○')+' <b>'+a.name+'</b> · '+a.desc+'</p>').join('')+(s.legacy?'<p class="subtle">구버전 업적·펫·퀘스트·장비 원본은 이전 기록으로 안전하게 보관 중입니다.</p>':'')};
 if(name==='relics')return {title:'이번 탐험의 유물',body:r?.relics.length?r.relics.map(k=>'<article class="item-card"><h3>'+RELICS[k].name+'</h3><p>'+RELICS[k].desc+'</p></article>').join(''):'<p>4·7구간에서 유물을 선택하세요.</p>'};
 if(name==='log')return {title:'전투 기록',body:r?.log.map(x=>'<p>'+esc(x)+'</p>').join('')||'<p>아직 기록이 없습니다.</p>'};
 if(name==='abandon')return {title:'이번 탐험에서 귀환할까요?',body:'<p>진행 중인 탐험을 종료하고 지금까지 얻은 골드와 장비를 가져갑니다.</p>'+btn('귀환하고 보상 받기','abandon','','primary')};
 return {title:'탐험 안내',body:'<p>9개 구간을 지나 잔불의 군주를 쓰러뜨리세요. 4·7구간에서는 이번 판에만 적용되는 유물을 얻습니다.</p><p><b>공격</b>은 자원을 1 회복합니다. <b>스킬</b>은 클래스마다 다릅니다. <b>방어</b>는 피해를 75% 줄이고 상태이상을 정화하며 다음 공격을 강화합니다.</p><p>적의 의도에 표시된 피해는 방어력 적용 전 수치입니다. 적이 강타·화염 폭풍을 준비하면 방어하세요.</p><p><b>키보드 1 / 2 / 3 / 4</b>로 공격·스킬·방어·물약을 사용합니다. Tab으로 이동하고 Enter로 선택합니다. Esc로 창을 닫습니다.</p><p>행동마다 자동 저장됩니다. 타이틀로 돌아가거나 새로고침해도 이어할 수 있습니다. 전투 중 나가도 시간은 흐르지만 적은 행동하지 않습니다. 다른 탭에서 기록이 바뀌면 진행을 멈추며, 최신 기록 불러오기로 이어갈 수 있습니다.</p>'+btn('세이브 백업 내려받기','export','','secondary')+'<h3>백업 가져오기</h3><p>이 게임에서 내려받은 V2 JSON 파일(최대 5MB)을 선택하세요. 복원 전 내용을 확인할 수 있습니다.</p><label for="save-import">세이브 JSON 파일</label><input id="save-import" type="file" accept=".json,application/json" aria-describedby="import-status"><p id="import-status" role="status" aria-live="polite"></p>'+btn('복원 전 기록 내려받기','export-previous','','secondary')};
}
